Repository uiowaSEP2024/003_MAGNA, pull requests merged in 2024-03, with the labels that each got.

#105 104 heroku auto deployment
  .github/workflows/deploy.yml
  .gitignore
  .idea/.gitignore
  prepare_runtime.py
Labels: type:bug, Points: 3

#120 Update README.md
  README.md
Labels: priority:low, state:pending

#119 51 travel auth form new
  features/home.feature
  features/login.feature
  features/steps/BrowserInitSteps.py
  features/steps/HomeSteps.py
  features/steps/LoginSteps.py
  features/steps/TravelAuthSteps.py
  features/steps/steps.py
  features/travel_auth.feature
  forms/admin.py
  forms/migrations/0007_travelauthorization.py
  forms/models.py
  forms/templates/travel_auth.html
  forms/templates/travel_auth_form.html
  forms/tests/test_travel_authorization.py
  forms/views.py
  magna/urls.py
  prepare_runtime.py
Labels: type:bug, type:feature, state:pending

#122 Heroku continuous deployment
  .github/workflows/deploy.yml
  modify_project_files_for_heroku.py
Labels: type:bug, type:feature, priority:medium

#124 Update README.md
  README.md
Labels: type:documentation, priority:low

#127 126 bug environment variables exposed in docker file
  Dockerfile
  docker-compose.yml
Labels: priority:critical, type:security, state:pending
